import type { CrudConfig } from "@/components/erp/CrudPage";
import * as d from "./data";

const S = (o: string[]) => ({ type: "select" as const, options: o });

export const leadsConfig: CrudConfig = {
  storeKey: "leads",
  title: "Leads Management",
  description: "Manage and track all real estate leads.",
  seed: d.leads,
  columns: [
    { key: "id", label: "Lead ID" },
    { key: "name", label: "Name" },
    { key: "phone", label: "Phone" },
    { key: "interest", label: "Interest" },
    { key: "city", label: "City" },
    { key: "source", label: "Source" },
    { key: "budget", label: "Budget" },
    { key: "agent", label: "Agent" },
    { key: "status", label: "Status", badge: true },
  ],
  fields: [
    { key: "name", label: "Full Name" },
    { key: "phone", label: "Phone", type: "tel" },
    { key: "email", label: "Email", type: "email" },
    { key: "city", label: "City", ...S(d.cities) },
    { key: "interest", label: "Interest", ...S(["Residential", "Commercial", "Plot", "Villa"]) },
    { key: "project", label: "Project", ...S(d.projectNames) },
    { key: "source", label: "Source", ...S(["Website", "Referral", "Social Media", "Walk-in", "Others"]) },
    { key: "budget", label: "Budget" },
    { key: "agent", label: "Assigned Agent", ...S(d.agents) },
    { key: "date", label: "Date", type: "date" },
    { key: "status", label: "Status", ...S(["New", "In Progress", "Interested", "Pending", "Cancelled"]) },
  ],
};

export const clientsConfig: CrudConfig = {
  storeKey: "clients",
  title: "Clients",
  description: "All onboarded clients and their portfolio value.",
  seed: d.clients,
  columns: [
    { key: "id", label: "Client ID" },
    { key: "name", label: "Name" },
    { key: "phone", label: "Phone" },
    { key: "email", label: "Email" },
    { key: "city", label: "City" },
    { key: "properties", label: "Properties" },
    { key: "totalValue", label: "Total Value" },
    { key: "status", label: "Status", badge: true },
  ],
  fields: [
    { key: "name", label: "Full Name" },
    { key: "phone", label: "Phone", type: "tel" },
    { key: "email", label: "Email", type: "email" },
    { key: "city", label: "City", ...S(d.cities) },
    { key: "properties", label: "Properties Owned", type: "number" },
    { key: "totalValue", label: "Total Value" },
    { key: "agent", label: "Relationship Manager", ...S(d.agents) },
    { key: "since", label: "Client Since", type: "date" },
    { key: "status", label: "Status", ...S(["Confirmed", "In Progress", "Pending"]) },
  ],
};

export const pipelineConfig: CrudConfig = {
  storeKey: "pipeline",
  title: "Sales Pipeline",
  description: "Track every deal from qualification to closure.",
  seed: d.pipeline,
  columns: [
    { key: "id", label: "Deal ID" },
    { key: "lead", label: "Lead" },
    { key: "project", label: "Project" },
    { key: "stage", label: "Stage", badge: true },
    { key: "value", label: "Deal Value" },
    { key: "probability", label: "Probability" },
    { key: "agent", label: "Agent" },
    { key: "status", label: "Status", badge: true },
  ],
  fields: [
    { key: "lead", label: "Lead Name" },
    { key: "project", label: "Project", ...S(d.projectNames) },
    { key: "stage", label: "Stage", ...S(["Leads", "Qualification", "Proposal", "Negotiation", "Closed"]) },
    { key: "value", label: "Deal Value" },
    { key: "probability", label: "Probability" },
    { key: "agent", label: "Agent", ...S(d.agents) },
    { key: "closeDate", label: "Expected Close", type: "date" },
    { key: "status", label: "Status", ...S(["In Progress", "Interested", "Pending", "Confirmed"]) },
  ],
};

export const followupsConfig: CrudConfig = {
  storeKey: "followups",
  title: "Follow-ups",
  description: "Scheduled calls, emails and meetings with prospects.",
  seed: d.followups,
  columns: [
    { key: "id", label: "ID" },
    { key: "lead", label: "Lead" },
    { key: "type", label: "Type" },
    { key: "dueDate", label: "Due Date" },
    { key: "time", label: "Time" },
    { key: "agent", label: "Agent" },
    { key: "status", label: "Status", badge: true },
  ],
  fields: [
    { key: "lead", label: "Lead Name" },
    { key: "type", label: "Type", ...S(["Call", "Email", "WhatsApp", "Meeting"]) },
    { key: "dueDate", label: "Due Date", type: "date" },
    { key: "time", label: "Time" },
    { key: "agent", label: "Agent", ...S(d.agents) },
    { key: "notes", label: "Notes", type: "textarea" },
    { key: "status", label: "Status", ...S(["Pending", "In Progress", "Confirmed", "Cancelled"]) },
  ],
};

export const projectsConfig: CrudConfig = {
  storeKey: "projects",
  title: "Projects",
  description: "All ongoing and completed real estate projects.",
  seed: d.projects,
  columns: [
    { key: "code", label: "Code" },
    { key: "name", label: "Project" },
    { key: "city", label: "City" },
    { key: "type", label: "Type" },
    { key: "totalUnits", label: "Units" },
    { key: "sold", label: "Sold" },
    { key: "price", label: "Price" },
    { key: "status", label: "Status", badge: true },
  ],
  fields: [
    { key: "name", label: "Project Name" },
    { key: "code", label: "Project Code" },
    { key: "developer", label: "Developer" },
    { key: "city", label: "City", ...S(d.cities) },
    { key: "location", label: "Address", full: true },
    { key: "type", label: "Project Type", ...S(["Residential", "Villa", "Commercial", "Plots"]) },
    { key: "totalUnits", label: "Total Units", type: "number" },
    { key: "sold", label: "Units Sold", type: "number" },
    { key: "launchDate", label: "Launch Date", type: "date" },
    { key: "possession", label: "Possession Date", type: "date" },
    { key: "price", label: "Starting Price" },
    { key: "status", label: "Status", ...S(["In Progress", "Confirmed", "Pending"]) },
    { key: "description", label: "Description", type: "textarea" },
    { key: "amenities", label: "Amenities", type: "textarea" },
    { key: "images", label: "Images", type: "file" },
  ],
};

export const propertiesConfig: CrudConfig = {
  storeKey: "properties",
  title: "Properties",
  description: "Complete inventory of listed properties.",
  seed: d.properties,
  columns: [
    { key: "id", label: "Property ID" },
    { key: "name", label: "Property" },
    { key: "project", label: "Project" },
    { key: "bhk", label: "BHK" },
    { key: "area", label: "Area" },
    { key: "floor", label: "Floor" },
    { key: "price", label: "Price" },
    { key: "status", label: "Status", badge: true },
  ],
  fields: [
    { key: "name", label: "Property Name" },
    { key: "project", label: "Project", ...S(d.projectNames) },
    { key: "bhk", label: "Configuration", ...S(["1 BHK", "2 BHK", "3 BHK", "4 BHK"]) },
    { key: "area", label: "Area (sq.ft)" },
    { key: "floor", label: "Floor", type: "number" },
    { key: "price", label: "Price" },
    { key: "city", label: "City", ...S(d.cities) },
    { key: "facing", label: "Facing", ...S(["East", "West", "North", "South", "North-East"]) },
    { key: "status", label: "Status", ...S(["Available", "Hold", "Booked", "Sold"]) },
  ],
};

export const bookingsConfig: CrudConfig = {
  storeKey: "bookings",
  title: "Bookings",
  description: "Track every property booking and its payment status.",
  seed: d.bookings,
  columns: [
    { key: "id", label: "Booking ID" },
    { key: "customer", label: "Customer" },
    { key: "property", label: "Property" },
    { key: "project", label: "Project" },
    { key: "agent", label: "Agent" },
    { key: "bookingDate", label: "Date" },
    { key: "amount", label: "Amount" },
    { key: "paymentStatus", label: "Payment", badge: true },
    { key: "status", label: "Status", badge: true },
  ],
  fields: [
    { key: "customer", label: "Customer" },
    { key: "property", label: "Property" },
    { key: "project", label: "Project", ...S(d.projectNames) },
    { key: "agent", label: "Agent", ...S(d.agents) },
    { key: "bookingDate", label: "Booking Date", type: "date" },
    { key: "amount", label: "Amount" },
    { key: "paymentStatus", label: "Payment Status", ...S(["Confirmed", "Pending", "In Progress"]) },
    { key: "status", label: "Booking Status", ...S(["Confirmed", "Pending", "Cancelled"]) },
  ],
};

export const inventoryConfig: CrudConfig = {
  storeKey: "inventory",
  title: "Inventory",
  description: "Unit-level availability across all towers and projects.",
  seed: d.inventory,
  columns: [
    { key: "unitNo", label: "Unit No" },
    { key: "project", label: "Project" },
    { key: "tower", label: "Tower" },
    { key: "floor", label: "Floor" },
    { key: "type", label: "Type" },
    { key: "bhk", label: "BHK" },
    { key: "area", label: "Area" },
    { key: "price", label: "Price" },
    { key: "customer", label: "Customer" },
    { key: "status", label: "Status", badge: true },
  ],
  fields: [
    { key: "unitNo", label: "Unit No" },
    { key: "project", label: "Project", ...S(d.projectNames) },
    { key: "tower", label: "Tower", ...S(["Tower A", "Tower B", "Tower C"]) },
    { key: "floor", label: "Floor", type: "number" },
    { key: "type", label: "Type", ...S(["Apartment", "Villa", "Plot", "Office"]) },
    { key: "bhk", label: "BHK", ...S(["1 BHK", "2 BHK", "3 BHK", "4 BHK"]) },
    { key: "area", label: "Area" },
    { key: "price", label: "Price" },
    { key: "customer", label: "Customer" },
    { key: "status", label: "Status", ...S(["Available", "Hold", "Booked", "Sold", "Blocked"]) },
  ],
};

export const siteVisitsConfig: CrudConfig = {
  storeKey: "site-visits",
  title: "Site Visits",
  description: "Plan and track client site visits across projects.",
  seed: d.siteVisits,
  columns: [
    { key: "id", label: "Visit ID" },
    { key: "client", label: "Client" },
    { key: "project", label: "Project" },
    { key: "city", label: "City" },
    { key: "date", label: "Date" },
    { key: "time", label: "Time" },
    { key: "agent", label: "Agent" },
    { key: "status", label: "Status", badge: true },
  ],
  fields: [
    { key: "client", label: "Client" },
    { key: "project", label: "Project", ...S(d.projectNames) },
    { key: "city", label: "City", ...S(d.cities) },
    { key: "date", label: "Date", type: "date" },
    { key: "time", label: "Time" },
    { key: "agent", label: "Agent", ...S(d.agents) },
    { key: "notes", label: "Notes", type: "textarea" },
    { key: "status", label: "Status", ...S(["Scheduled", "Completed", "Rescheduled", "Cancelled"]) },
  ],
};

export const paymentsConfig: CrudConfig = {
  storeKey: "payments",
  title: "Payments",
  description: "Collections, pending dues and payment history.",
  seed: d.payments,
  columns: [
    { key: "id", label: "Payment ID" },
    { key: "customer", label: "Customer" },
    { key: "booking", label: "Booking" },
    { key: "mode", label: "Mode" },
    { key: "amount", label: "Amount" },
    { key: "date", label: "Date" },
    { key: "status", label: "Status", badge: true },
  ],
  fields: [
    { key: "customer", label: "Customer" },
    { key: "booking", label: "Booking ID" },
    { key: "mode", label: "Payment Mode", ...S(["NEFT", "Cheque", "UPI", "Bank Loan", "Cash"]) },
    { key: "amount", label: "Amount" },
    { key: "date", label: "Date", type: "date" },
    { key: "status", label: "Status", ...S(["Confirmed", "Pending", "Cancelled"]) },
  ],
};

export const invoicesConfig: CrudConfig = {
  storeKey: "invoices",
  title: "Invoices",
  description: "GST invoices raised against bookings.",
  seed: d.invoices,
  columns: [
    { key: "id", label: "Invoice No" },
    { key: "customer", label: "Customer" },
    { key: "booking", label: "Booking" },
    { key: "amount", label: "Amount" },
    { key: "tax", label: "Tax" },
    { key: "total", label: "Total" },
    { key: "dueDate", label: "Due Date" },
    { key: "status", label: "Status", badge: true },
  ],
  fields: [
    { key: "customer", label: "Customer" },
    { key: "booking", label: "Booking ID" },
    { key: "amount", label: "Amount" },
    { key: "tax", label: "Tax" },
    { key: "total", label: "Total" },
    { key: "dueDate", label: "Due Date", type: "date" },
    { key: "status", label: "Status", ...S(["Confirmed", "Pending", "Cancelled"]) },
  ],
};

export const expensesConfig: CrudConfig = {
  storeKey: "expenses",
  title: "Expenses",
  description: "Operational and project expenses.",
  seed: d.expenses,
  columns: [
    { key: "id", label: "Expense ID" },
    { key: "category", label: "Category" },
    { key: "description", label: "Description" },
    { key: "amount", label: "Amount" },
    { key: "date", label: "Date" },
    { key: "addedBy", label: "Added By" },
    { key: "status", label: "Status", badge: true },
  ],
  fields: [
    { key: "category", label: "Category", ...S(["Marketing", "Construction", "Salaries", "Office", "Legal"]) },
    { key: "description", label: "Description", full: true },
    { key: "amount", label: "Amount" },
    { key: "date", label: "Date", type: "date" },
    { key: "addedBy", label: "Added By", ...S(d.agents) },
    { key: "status", label: "Status", ...S(["Confirmed", "Pending"]) },
  ],
};

export const teamConfig: CrudConfig = {
  storeKey: "team",
  title: "Team Management",
  description: "Employees, roles and departments.",
  seed: d.team,
  columns: [
    { key: "id", label: "Employee ID" },
    { key: "name", label: "Name" },
    { key: "role", label: "Role" },
    { key: "department", label: "Department" },
    { key: "phone", label: "Phone" },
    { key: "city", label: "City" },
    { key: "joined", label: "Joined" },
    { key: "status", label: "Status", badge: true },
  ],
  fields: [
    { key: "name", label: "Full Name" },
    { key: "role", label: "Role", ...S(["Sales Manager", "Sales Executive", "Property Manager", "Accountant", "HR", "Agent"]) },
    { key: "department", label: "Department", ...S(["Sales", "Finance", "Operations", "Marketing"]) },
    { key: "phone", label: "Phone", type: "tel" },
    { key: "email", label: "Email", type: "email" },
    { key: "city", label: "City", ...S(d.cities) },
    { key: "joined", label: "Joining Date", type: "date" },
    { key: "status", label: "Status", ...S(["Confirmed", "Pending"]) },
  ],
};

export const documentsConfig: CrudConfig = {
  storeKey: "documents",
  title: "Documents",
  description: "Agreements, legal papers and project documents.",
  seed: d.documents,
  columns: [
    { key: "id", label: "Doc ID" },
    { key: "name", label: "Document" },
    { key: "type", label: "Type" },
    { key: "project", label: "Project" },
    { key: "size", label: "Size" },
    { key: "uploadedBy", label: "Uploaded By" },
    { key: "date", label: "Date" },
    { key: "status", label: "Status", badge: true },
  ],
  fields: [
    { key: "name", label: "Document Name" },
    { key: "type", label: "Type", ...S(["Agreement", "Legal", "Plan", "Receipt"]) },
    { key: "project", label: "Project", ...S(d.projectNames) },
    { key: "file", label: "Upload File", type: "file" },
    { key: "uploadedBy", label: "Uploaded By", ...S(d.agents) },
    { key: "date", label: "Date", type: "date" },
    { key: "status", label: "Status", ...S(["Confirmed", "Pending"]) },
  ],
};

export const campaignsConfig: CrudConfig = {
  storeKey: "campaigns",
  title: "Campaigns",
  description: "Marketing campaign performance and ROI.",
  seed: d.campaigns,
  columns: [
    { key: "id", label: "Campaign ID" },
    { key: "name", label: "Campaign" },
    { key: "channel", label: "Channel" },
    { key: "budget", label: "Budget" },
    { key: "leads", label: "Leads" },
    { key: "conversions", label: "Conversions" },
    { key: "roi", label: "ROI" },
    { key: "status", label: "Status", badge: true },
  ],
  fields: [
    { key: "name", label: "Campaign Name" },
    { key: "channel", label: "Channel", ...S(["Google", "Facebook", "Instagram", "Website", "WhatsApp", "Email"]) },
    { key: "budget", label: "Budget" },
    { key: "leads", label: "Leads", type: "number" },
    { key: "conversions", label: "Conversions", type: "number" },
    { key: "roi", label: "ROI" },
    { key: "status", label: "Status", ...S(["In Progress", "Confirmed", "Pending"]) },
  ],
};

export const enquiriesConfig: CrudConfig = {
  storeKey: "enquiries",
  title: "Enquiries",
  description: "Inbound enquiries from all marketing channels.",
  seed: d.enquiries,
  columns: [
    { key: "id", label: "Enquiry ID" },
    { key: "name", label: "Name" },
    { key: "phone", label: "Phone" },
    { key: "property", label: "Property" },
    { key: "source", label: "Source" },
    { key: "date", label: "Date" },
    { key: "assignedTo", label: "Assigned To" },
    { key: "status", label: "Status", badge: true },
  ],
  fields: [
    { key: "name", label: "Name" },
    { key: "phone", label: "Phone", type: "tel" },
    { key: "email", label: "Email", type: "email" },
    { key: "property", label: "Property Interest" },
    { key: "source", label: "Source", ...S(["Website", "Facebook", "WhatsApp", "Walk-in", "Google"]) },
    { key: "date", label: "Date", type: "date" },
    { key: "assignedTo", label: "Assigned To", ...S(d.agents) },
    { key: "message", label: "Message", type: "textarea" },
    { key: "status", label: "Status", ...S(["New", "In Progress", "Pending", "Confirmed"]) },
  ],
};

export const usersConfig: CrudConfig = {
  storeKey: "users",
  title: "Users & Roles",
  description: "Manage system users, roles and permissions.",
  seed: d.users,
  columns: [
    { key: "id", label: "User ID" },
    { key: "name", label: "Name" },
    { key: "email", label: "Email" },
    { key: "role", label: "Role" },
    { key: "lastLogin", label: "Last Login" },
    { key: "status", label: "Status", badge: true },
  ],
  fields: [
    { key: "name", label: "Full Name" },
    { key: "email", label: "Email", type: "email" },
    { key: "role", label: "Role", ...S(["Super Admin", "Admin", "Sales Manager", "Sales Executive", "Property Manager", "Accountant", "HR", "Agent"]) },
    { key: "status", label: "Status", ...S(["Confirmed", "Pending"]) },
  ],
};

export const tasksConfig: CrudConfig = {
  storeKey: "tasks",
  title: "Tasks",
  description: "Team task board across all departments.",
  seed: d.tasks,
  columns: [
    { key: "id", label: "Task ID" },
    { key: "title", label: "Task" },
    { key: "assignee", label: "Assignee" },
    { key: "priority", label: "Priority" },
    { key: "dueDate", label: "Due Date" },
    { key: "stage", label: "Stage", badge: true },
  ],
  fields: [
    { key: "title", label: "Task Title", full: true },
    { key: "assignee", label: "Assignee", ...S(d.agents) },
    { key: "priority", label: "Priority", ...S(["High", "Medium", "Low"]) },
    { key: "dueDate", label: "Due Date", type: "date" },
    { key: "stage", label: "Stage", ...S(["To Do", "In Progress", "Review", "Completed"]) },
    { key: "status", label: "Status", ...S(["Pending", "In Progress", "Confirmed"]) },
  ],
};
