/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as EnquiriesRouteImport } from './routes/enquiries'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as FollowupsRouteImport } from './routes/followups'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SiteVisitsRouteImport } from './routes/site-visits'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TeamRouteImport } from './routes/team'
import { Route as UsersRolesRouteImport } from './routes/users-roles'
import { Route as AdminMastersBdayAnnivRouteImport } from './routes/admin/masters/bday-anniv'
import { Route as AdminMastersBrokerRouteImport } from './routes/admin/masters/broker'
import { Route as AdminMastersBudgetRouteImport } from './routes/admin/masters/budget'
import { Route as AdminMastersCustomerRouteImport } from './routes/admin/masters/customer'
import { Route as AdminMastersExpenseEntryRouteImport } from './routes/admin/masters/expense-entry'
import { Route as AdminMastersGeneralRouteImport } from './routes/admin/masters/general'
import { Route as AdminMastersInquiryStatusRouteImport } from './routes/admin/masters/inquiry-status'
import { Route as AdminMastersLocalityRouteImport } from './routes/admin/masters/locality'
import { Route as AdminMastersSourceRouteImport } from './routes/admin/masters/source'
import { Route as AdminMastersVisitorEntryRouteImport } from './routes/admin/masters/visitor-entry'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiriesRoute = EnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowupsRoute = FollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteVisitsRoute = SiteVisitsRouteImport.update({
  id: '/site-visits',
  path: '/site-visits',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRolesRoute = UsersRolesRouteImport.update({
  id: '/users-roles',
  path: '/users-roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMastersBdayAnnivRoute = AdminMastersBdayAnnivRouteImport.update({
  id: '/admin/masters/bday-anniv',
  path: '/admin/masters/bday-anniv',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMastersBrokerRoute = AdminMastersBrokerRouteImport.update({
  id: '/admin/masters/broker',
  path: '/admin/masters/broker',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMastersBudgetRoute = AdminMastersBudgetRouteImport.update({
  id: '/admin/masters/budget',
  path: '/admin/masters/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMastersCustomerRoute = AdminMastersCustomerRouteImport.update({
  id: '/admin/masters/customer',
  path: '/admin/masters/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMastersExpenseEntryRoute =
  AdminMastersExpenseEntryRouteImport.update({
    id: '/admin/masters/expense-entry',
    path: '/admin/masters/expense-entry',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminMastersGeneralRoute = AdminMastersGeneralRouteImport.update({
  id: '/admin/masters/general',
  path: '/admin/masters/general',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMastersInquiryStatusRoute =
  AdminMastersInquiryStatusRouteImport.update({
    id: '/admin/masters/inquiry-status',
    path: '/admin/masters/inquiry-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminMastersLocalityRoute = AdminMastersLocalityRouteImport.update({
  id: '/admin/masters/locality',
  path: '/admin/masters/locality',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMastersSourceRoute = AdminMastersSourceRouteImport.update({
  id: '/admin/masters/source',
  path: '/admin/masters/source',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMastersVisitorEntryRoute =
  AdminMastersVisitorEntryRouteImport.update({
    id: '/admin/masters/visitor-entry',
    path: '/admin/masters/visitor-entry',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/calendar': typeof CalendarRoute
  '/campaigns': typeof CampaignsRoute
  '/clients': typeof ClientsRoute
  '/documents': typeof DocumentsRoute
  '/enquiries': typeof EnquiriesRoute
  '/expenses': typeof ExpensesRoute
  '/followups': typeof FollowupsRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/leads': typeof LeadsRoute
  '/notifications': typeof NotificationsRoute
  '/organization': typeof OrganizationRoute
  '/payments': typeof PaymentsRoute
  '/pipeline': typeof PipelineRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/properties': typeof PropertiesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/site-visits': typeof SiteVisitsRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/users-roles': typeof UsersRolesRoute
  '/admin/masters/bday-anniv': typeof AdminMastersBdayAnnivRoute
  '/admin/masters/broker': typeof AdminMastersBrokerRoute
  '/admin/masters/budget': typeof AdminMastersBudgetRoute
  '/admin/masters/customer': typeof AdminMastersCustomerRoute
  '/admin/masters/expense-entry': typeof AdminMastersExpenseEntryRoute
  '/admin/masters/general': typeof AdminMastersGeneralRoute
  '/admin/masters/inquiry-status': typeof AdminMastersInquiryStatusRoute
  '/admin/masters/locality': typeof AdminMastersLocalityRoute
  '/admin/masters/source': typeof AdminMastersSourceRoute
  '/admin/masters/visitor-entry': typeof AdminMastersVisitorEntryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/calendar': typeof CalendarRoute
  '/campaigns': typeof CampaignsRoute
  '/clients': typeof ClientsRoute
  '/documents': typeof DocumentsRoute
  '/enquiries': typeof EnquiriesRoute
  '/expenses': typeof ExpensesRoute
  '/followups': typeof FollowupsRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/leads': typeof LeadsRoute
  '/notifications': typeof NotificationsRoute
  '/organization': typeof OrganizationRoute
  '/payments': typeof PaymentsRoute
  '/pipeline': typeof PipelineRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/properties': typeof PropertiesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/site-visits': typeof SiteVisitsRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/users-roles': typeof UsersRolesRoute
  '/admin/masters/bday-anniv': typeof AdminMastersBdayAnnivRoute
  '/admin/masters/broker': typeof AdminMastersBrokerRoute
  '/admin/masters/budget': typeof AdminMastersBudgetRoute
  '/admin/masters/customer': typeof AdminMastersCustomerRoute
  '/admin/masters/expense-entry': typeof AdminMastersExpenseEntryRoute
  '/admin/masters/general': typeof AdminMastersGeneralRoute
  '/admin/masters/inquiry-status': typeof AdminMastersInquiryStatusRoute
  '/admin/masters/locality': typeof AdminMastersLocalityRoute
  '/admin/masters/source': typeof AdminMastersSourceRoute
  '/admin/masters/visitor-entry': typeof AdminMastersVisitorEntryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/calendar': typeof CalendarRoute
  '/campaigns': typeof CampaignsRoute
  '/clients': typeof ClientsRoute
  '/documents': typeof DocumentsRoute
  '/enquiries': typeof EnquiriesRoute
  '/expenses': typeof ExpensesRoute
  '/followups': typeof FollowupsRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/leads': typeof LeadsRoute
  '/notifications': typeof NotificationsRoute
  '/organization': typeof OrganizationRoute
  '/payments': typeof PaymentsRoute
  '/pipeline': typeof PipelineRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/properties': typeof PropertiesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/site-visits': typeof SiteVisitsRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/users-roles': typeof UsersRolesRoute
  '/admin/masters/bday-anniv': typeof AdminMastersBdayAnnivRoute
  '/admin/masters/broker': typeof AdminMastersBrokerRoute
  '/admin/masters/budget': typeof AdminMastersBudgetRoute
  '/admin/masters/customer': typeof AdminMastersCustomerRoute
  '/admin/masters/expense-entry': typeof AdminMastersExpenseEntryRoute
  '/admin/masters/general': typeof AdminMastersGeneralRoute
  '/admin/masters/inquiry-status': typeof AdminMastersInquiryStatusRoute
  '/admin/masters/locality': typeof AdminMastersLocalityRoute
  '/admin/masters/source': typeof AdminMastersSourceRoute
  '/admin/masters/visitor-entry': typeof AdminMastersVisitorEntryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/calendar'
    | '/campaigns'
    | '/clients'
    | '/documents'
    | '/enquiries'
    | '/expenses'
    | '/followups'
    | '/inventory'
    | '/invoices'
    | '/leads'
    | '/notifications'
    | '/organization'
    | '/payments'
    | '/pipeline'
    | '/profile'
    | '/projects'
    | '/properties'
    | '/reports'
    | '/settings'
    | '/site-visits'
    | '/tasks'
    | '/team'
    | '/users-roles'
    | '/admin/masters/bday-anniv'
    | '/admin/masters/broker'
    | '/admin/masters/budget'
    | '/admin/masters/customer'
    | '/admin/masters/expense-entry'
    | '/admin/masters/general'
    | '/admin/masters/inquiry-status'
    | '/admin/masters/locality'
    | '/admin/masters/source'
    | '/admin/masters/visitor-entry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/calendar'
    | '/campaigns'
    | '/clients'
    | '/documents'
    | '/enquiries'
    | '/expenses'
    | '/followups'
    | '/inventory'
    | '/invoices'
    | '/leads'
    | '/notifications'
    | '/organization'
    | '/payments'
    | '/pipeline'
    | '/profile'
    | '/projects'
    | '/properties'
    | '/reports'
    | '/settings'
    | '/site-visits'
    | '/tasks'
    | '/team'
    | '/users-roles'
    | '/admin/masters/bday-anniv'
    | '/admin/masters/broker'
    | '/admin/masters/budget'
    | '/admin/masters/customer'
    | '/admin/masters/expense-entry'
    | '/admin/masters/general'
    | '/admin/masters/inquiry-status'
    | '/admin/masters/locality'
    | '/admin/masters/source'
    | '/admin/masters/visitor-entry'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/calendar'
    | '/campaigns'
    | '/clients'
    | '/documents'
    | '/enquiries'
    | '/expenses'
    | '/followups'
    | '/inventory'
    | '/invoices'
    | '/leads'
    | '/notifications'
    | '/organization'
    | '/payments'
    | '/pipeline'
    | '/profile'
    | '/projects'
    | '/properties'
    | '/reports'
    | '/settings'
    | '/site-visits'
    | '/tasks'
    | '/team'
    | '/users-roles'
    | '/admin/masters/bday-anniv'
    | '/admin/masters/broker'
    | '/admin/masters/budget'
    | '/admin/masters/customer'
    | '/admin/masters/expense-entry'
    | '/admin/masters/general'
    | '/admin/masters/inquiry-status'
    | '/admin/masters/locality'
    | '/admin/masters/source'
    | '/admin/masters/visitor-entry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRoute
  CalendarRoute: typeof CalendarRoute
  CampaignsRoute: typeof CampaignsRoute
  ClientsRoute: typeof ClientsRoute
  DocumentsRoute: typeof DocumentsRoute
  EnquiriesRoute: typeof EnquiriesRoute
  ExpensesRoute: typeof ExpensesRoute
  FollowupsRoute: typeof FollowupsRoute
  InventoryRoute: typeof InventoryRoute
  InvoicesRoute: typeof InvoicesRoute
  LeadsRoute: typeof LeadsRoute
  NotificationsRoute: typeof NotificationsRoute
  OrganizationRoute: typeof OrganizationRoute
  PaymentsRoute: typeof PaymentsRoute
  PipelineRoute: typeof PipelineRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  PropertiesRoute: typeof PropertiesRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SiteVisitsRoute: typeof SiteVisitsRoute
  TasksRoute: typeof TasksRoute
  TeamRoute: typeof TeamRoute
  UsersRolesRoute: typeof UsersRolesRoute
  AdminMastersBdayAnnivRoute: typeof AdminMastersBdayAnnivRoute
  AdminMastersBrokerRoute: typeof AdminMastersBrokerRoute
  AdminMastersBudgetRoute: typeof AdminMastersBudgetRoute
  AdminMastersCustomerRoute: typeof AdminMastersCustomerRoute
  AdminMastersExpenseEntryRoute: typeof AdminMastersExpenseEntryRoute
  AdminMastersGeneralRoute: typeof AdminMastersGeneralRoute
  AdminMastersInquiryStatusRoute: typeof AdminMastersInquiryStatusRoute
  AdminMastersLocalityRoute: typeof AdminMastersLocalityRoute
  AdminMastersSourceRoute: typeof AdminMastersSourceRoute
  AdminMastersVisitorEntryRoute: typeof AdminMastersVisitorEntryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiries': {
      id: '/enquiries'
      path: '/enquiries'
      fullPath: '/enquiries'
      preLoaderRoute: typeof EnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/followups': {
      id: '/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof FollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-visits': {
      id: '/site-visits'
      path: '/site-visits'
      fullPath: '/site-visits'
      preLoaderRoute: typeof SiteVisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users-roles': {
      id: '/users-roles'
      path: '/users-roles'
      fullPath: '/users-roles'
      preLoaderRoute: typeof UsersRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/masters/bday-anniv': {
      id: '/admin/masters/bday-anniv'
      path: '/admin/masters/bday-anniv'
      fullPath: '/admin/masters/bday-anniv'
      preLoaderRoute: typeof AdminMastersBdayAnnivRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/masters/broker': {
      id: '/admin/masters/broker'
      path: '/admin/masters/broker'
      fullPath: '/admin/masters/broker'
      preLoaderRoute: typeof AdminMastersBrokerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/masters/budget': {
      id: '/admin/masters/budget'
      path: '/admin/masters/budget'
      fullPath: '/admin/masters/budget'
      preLoaderRoute: typeof AdminMastersBudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/masters/customer': {
      id: '/admin/masters/customer'
      path: '/admin/masters/customer'
      fullPath: '/admin/masters/customer'
      preLoaderRoute: typeof AdminMastersCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/masters/expense-entry': {
      id: '/admin/masters/expense-entry'
      path: '/admin/masters/expense-entry'
      fullPath: '/admin/masters/expense-entry'
      preLoaderRoute: typeof AdminMastersExpenseEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/masters/general': {
      id: '/admin/masters/general'
      path: '/admin/masters/general'
      fullPath: '/admin/masters/general'
      preLoaderRoute: typeof AdminMastersGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/masters/inquiry-status': {
      id: '/admin/masters/inquiry-status'
      path: '/admin/masters/inquiry-status'
      fullPath: '/admin/masters/inquiry-status'
      preLoaderRoute: typeof AdminMastersInquiryStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/masters/locality': {
      id: '/admin/masters/locality'
      path: '/admin/masters/locality'
      fullPath: '/admin/masters/locality'
      preLoaderRoute: typeof AdminMastersLocalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/masters/source': {
      id: '/admin/masters/source'
      path: '/admin/masters/source'
      fullPath: '/admin/masters/source'
      preLoaderRoute: typeof AdminMastersSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/masters/visitor-entry': {
      id: '/admin/masters/visitor-entry'
      path: '/admin/masters/visitor-entry'
      fullPath: '/admin/masters/visitor-entry'
      preLoaderRoute: typeof AdminMastersVisitorEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRoute,
  CalendarRoute: CalendarRoute,
  CampaignsRoute: CampaignsRoute,
  ClientsRoute: ClientsRoute,
  DocumentsRoute: DocumentsRoute,
  EnquiriesRoute: EnquiriesRoute,
  ExpensesRoute: ExpensesRoute,
  FollowupsRoute: FollowupsRoute,
  InventoryRoute: InventoryRoute,
  InvoicesRoute: InvoicesRoute,
  LeadsRoute: LeadsRoute,
  NotificationsRoute: NotificationsRoute,
  OrganizationRoute: OrganizationRoute,
  PaymentsRoute: PaymentsRoute,
  PipelineRoute: PipelineRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  PropertiesRoute: PropertiesRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SiteVisitsRoute: SiteVisitsRoute,
  TasksRoute: TasksRoute,
  TeamRoute: TeamRoute,
  UsersRolesRoute: UsersRolesRoute,
  AdminMastersBdayAnnivRoute: AdminMastersBdayAnnivRoute,
  AdminMastersBrokerRoute: AdminMastersBrokerRoute,
  AdminMastersBudgetRoute: AdminMastersBudgetRoute,
  AdminMastersCustomerRoute: AdminMastersCustomerRoute,
  AdminMastersExpenseEntryRoute: AdminMastersExpenseEntryRoute,
  AdminMastersGeneralRoute: AdminMastersGeneralRoute,
  AdminMastersInquiryStatusRoute: AdminMastersInquiryStatusRoute,
  AdminMastersLocalityRoute: AdminMastersLocalityRoute,
  AdminMastersSourceRoute: AdminMastersSourceRoute,
  AdminMastersVisitorEntryRoute: AdminMastersVisitorEntryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
